version: "3"

services:
  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "${TYPEORM_PORT}"
    ports:
      - "${TYPEORM_PORT}:5432"
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}

  test:
    image: postgres:11-alpine
    working_dir: /server
    command: sh -c "yarn && yarn test"
    depends_on:
      - database