version: "3"

services:
  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5433"
    ports:
      - "${TYPEORM_PORT}:5432"
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: dickson-melo
